<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkinDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $skins = [
            [
                'skin_id' => 0,
                'skin_model_name' => 'cj',
                'name' => 'Carl \"CJ\" Johnson (Main Character)',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Grove Street Families',
                'usable' => false,
            ],
            [
                'skin_id' => 1,
                'skin_model_name' => 'truth',
                'name' => 'The Truth',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 2,
                'skin_model_name' => 'maccer',
                'name' => 'Maccer',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 3,
                'skin_model_name' => 'andre',
                'name' => 'Andre',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 4,
                'skin_model_name' => 'bbthin',
                'name' => 'Barry "Big Bear" Thorne[Thin]',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Grove Street Families',
                'usable' => true,
            ],
            [
                'skin_id' => 5,
                'skin_model_name' => 'bb',
                'name' => 'Barry "Big Bear" Thorne[Big]',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Grove Street Families',
                'usable' => true,
            ],
            [
                'skin_id' => 6,
                'skin_model_name' => 'emmet',
                'name' => 'Emmet',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 7,
                'skin_model_name' => 'male01',
                'name' => 'Taxi Driver/Train Driver',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 8,
                'skin_model_name' => 'janitor',
                'name' => 'Janitor',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 9,
                'skin_model_name' => 'bfori',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 10,
                'skin_model_name' => 'bfost',
                'name' => 'Old Woman',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 11,
                'skin_model_name' => 'vbfycrp',
                'name' => 'Casino croupier',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 12,
                'skin_model_name' => 'bfyri',
                'name' => 'Rich Woman',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 13,
                'skin_model_name' => 'bfyst',
                'name' => 'Street Girl',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 14,
                'skin_model_name' => 'bmori',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 15,
                'skin_model_name' => 'bmost',
                'name' => 'Mr.Whittaker (RS Haul Owner)',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 16,
                'skin_model_name' => 'bmyap',
                'name' => 'Airport Ground Worker',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 17,
                'skin_model_name' => 'bmybu',
                'name' => 'Businessman',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 18,
                'skin_model_name' => 'bmybe',
                'name' => 'Beach Visitor',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 19,
                'skin_model_name' => 'bmydj',
                'name' => 'DJ',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 20,
                'skin_model_name' => 'bmyri',
                'name' => 'Rich Guy (Madd Dogg\'s Manager)',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 21,
                'skin_model_name' => 'bmycr',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 22,
                'skin_model_name' => 'bmyst',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 23,
                'skin_model_name' => 'wmybmx',
                'name' => 'BMXer',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 24,
                'skin_model_name' => 'wbdyg1',
                'name' => 'Madd Dogg Bodyguard',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 25,
                'skin_model_name' => 'wbdyg2',
                'name' => 'Madd Dogg Bodyguard',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 26,
                'skin_model_name' => 'wmybp',
                'name' => 'Backpacker',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 27,
                'skin_model_name' => 'wmycon',
                'name' => 'Construction Worker',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 28,
                'skin_model_name' => 'bmydrug',
                'name' => 'Drug Dealer',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 29,
                'skin_model_name' => 'wmydrug',
                'name' => 'Drug Dealer',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 30,
                'skin_model_name' => 'hmydrug',
                'name' => 'Drug Dealer',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 31,
                'skin_model_name' => 'dwfolc',
                'name' => 'Farm - Town inhabitant',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 32,
                'skin_model_name' => 'dwmolc1',
                'name' => 'Farm - Town inhabitant',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 33,
                'skin_model_name' => 'dwmolc2',
                'name' => 'Farm - Town inhabitant',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 34,
                'skin_model_name' => 'dwmylc1',
                'name' => 'Farm - Town inhabitant',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 35,
                'skin_model_name' => 'hmogar',
                'name' => 'Gardener',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 36,
                'skin_model_name' => 'wmygol1',
                'name' => 'Golfer',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 37,
                'skin_model_name' => 'wmygol2',
                'name' => 'Golfer',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 38,
                'skin_model_name' => 'hfori',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 39,
                'skin_model_name' => 'hfost',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 40,
                'skin_model_name' => 'hfyri',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 41,
                'skin_model_name' => 'hfyst',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 42,
                'skin_model_name' => 'jethro',
                'name' => 'Jethro',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 43,
                'skin_model_name' => 'hmori',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 44,
                'skin_model_name' => 'hmost',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 45,
                'skin_model_name' => 'hmybe',
                'name' => 'Beach Visitor',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 46,
                'skin_model_name' => 'hmyri',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 47,
                'skin_model_name' => 'hmycr',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 48,
                'skin_model_name' => 'hmyst',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 49,
                'skin_model_name' => 'omokung',
                'name' => 'Snakehead(Da Nang)',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 50,
                'skin_model_name' => 'wmymech',
                'name' => 'Mechanic',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 51,
                'skin_model_name' => 'bmymoun',
                'name' => 'Mountain Biker',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 52,
                'skin_model_name' => 'wmymoun',
                'name' => 'Mountain Biker',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 53,
                'skin_model_name' => 'ofori',
                'name' => 'Asian Female Ped',
                'gender' => 'female',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 54,
                'skin_model_name' => 'ofost',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 55,
                'skin_model_name' => 'ofyri',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 56,
                'skin_model_name' => 'ofyst',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 57,
                'skin_model_name' => 'omori',
                'name' => 'Oriental Ped',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 58,
                'skin_model_name' => 'omost',
                'name' => 'Oriental Ped',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 59,
                'skin_model_name' => 'omyri',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 60,
                'skin_model_name' => 'omyst',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 61,
                'skin_model_name' => 'wmyplt',
                'name' => 'Pilot',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 62,
                'skin_model_name' => 'wmopj',
                'name' => 'Colonel Fuhrberger',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 63,
                'skin_model_name' => 'bfypro',
                'name' => 'Prostitute',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 64,
                'skin_model_name' => 'hfypro',
                'name' => 'Prostitute',
                'gender' => 'female',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 65,
                'skin_model_name' => 'kendl',
                'name' => 'Kendl Johnson',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 66,
                'skin_model_name' => 'bmypol1',
                'name' => 'Pool Player',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 67,
                'skin_model_name' => 'bmypol2',
                'name' => 'Pool Player',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 68,
                'skin_model_name' => 'wmoprea',
                'name' => 'Priest / Preacher',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 69,
                'skin_model_name' => 'sbfyst',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 70,
                'skin_model_name' => 'wmosci',
                'name' => 'Scientist',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 71,
                'skin_model_name' => 'wmysgrd',
                'name' => 'Security Guard',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 72,
                'skin_model_name' => 'swmyhp1',
                'name' => 'Hippy',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 73,
                'skin_model_name' => 'swmyhp2',
                'name' => 'Hippy',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 75,
                'skin_model_name' => 'swfopro',
                'name' => 'Prostitute',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 76,
                'skin_model_name' => 'wfystew',
                'name' => 'Stewardess',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 77,
                'skin_model_name' => 'swmotr1',
                'name' => 'Homeless',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 78,
                'skin_model_name' => 'wmotr1',
                'name' => 'Homeless',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 79,
                'skin_model_name' => 'bmotr1',
                'name' => 'Homeless',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 80,
                'skin_model_name' => 'vbmybox',
                'name' => 'Boxer',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 81,
                'skin_model_name' => 'vwmybox',
                'name' => 'Boxer',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 82,
                'skin_model_name' => 'vhmyelv',
                'name' => 'Black Elvis',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 83,
                'skin_model_name' => 'vbmyelv',
                'name' => 'White Elvis',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 84,
                'skin_model_name' => 'vimyelv',
                'name' => 'Blue Elvis',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 85,
                'skin_model_name' => 'vwfypro',
                'name' => 'Prostitute',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 86,
                'skin_model_name' => 'ryder3',
                'name' => 'Ryder with robbery mask',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 87,
                'skin_model_name' => 'vwfyst1',
                'name' => 'Stripper',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 88,
                'skin_model_name' => 'wfori',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 89,
                'skin_model_name' => 'wfost',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 90,
                'skin_model_name' => 'wfyjg',
                'name' => 'Jogger',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 91,
                'skin_model_name' => 'wfyri',
                'name' => 'Rich Woman',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 92,
                'skin_model_name' => 'wfyro',
                'name' => 'Rollerskater',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 93,
                'skin_model_name' => 'wfyst',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 94,
                'skin_model_name' => 'wmori',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 95,
                'skin_model_name' => 'wmost',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 96,
                'skin_model_name' => 'wmyjg',
                'name' => 'Jogger',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 97,
                'skin_model_name' => 'wmylg',
                'name' => 'Lifeguard',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 98,
                'skin_model_name' => 'wmyri',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 99,
                'skin_model_name' => 'wmyro',
                'name' => 'Rollerskater',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 100,
                'skin_model_name' => 'wmycr',
                'name' => 'Biker',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Biker',
                'usable' => true,
            ],
            [
                'skin_id' => 101,
                'skin_model_name' => 'wmyst',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 102,
                'skin_model_name' => 'ballas1',
                'name' => 'Balla 1',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Ballas',
                'usable' => true,
            ],
            [
                'skin_id' => 103,
                'skin_model_name' => 'ballas2',
                'name' => 'Balla 2',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Ballas',
                'usable' => true,
            ],
            [
                'skin_id' => 104,
                'skin_model_name' => 'ballas3',
                'name' => 'Balla 3',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Ballas',
                'usable' => true,
            ],
            [
                'skin_id' => 105,
                'skin_model_name' => 'fam1',
                'name' => 'Grove Street Families 1',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Grove Street Families',
                'usable' => true,
            ],
            [
                'skin_id' => 106,
                'skin_model_name' => 'fam2',
                'name' => 'Grove Street Families 2',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Grove Street Families',
                'usable' => true,
            ],
            [
                'skin_id' => 107,
                'skin_model_name' => 'fam3',
                'name' => 'Grove Street Families 3',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Grove Street Families',
                'usable' => true,
            ],
            [
                'skin_id' => 108,
                'skin_model_name' => 'lsv1',
                'name' => 'Los Santos Vagos 1',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Los Santos Vagos',
                'usable' => true,
            ],
            [
                'skin_id' => 109,
                'skin_model_name' => 'lsv2',
                'name' => 'Los Santos Vagos 2',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Los Santos Vagos',
                'usable' => true,
            ],
            [
                'skin_id' => 110,
                'skin_model_name' => 'lsv3',
                'name' => 'Los Santos Vagos 3',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Los Santos Vagos',
                'usable' => true,
            ],
            [
                'skin_id' => 111,
                'skin_model_name' => 'maffa',
                'name' => 'The Russian Mafia 1',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'The Russian Mafia',
                'usable' => true,
            ],
            [
                'skin_id' => 112,
                'skin_model_name' => 'maffb',
                'name' => 'The Russian Mafia 2',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'The Russian Mafia',
                'usable' => true,
            ],
            [
                'skin_id' => 113,
                'skin_model_name' => 'mafboss',
                'name' => 'The Russian Mafia 3',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'The Russian Mafia',
                'usable' => true,
            ],
            [
                'skin_id' => 114,
                'skin_model_name' => 'vla1',
                'name' => 'Varios Los Aztecas 1',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Varios Los Aztecas',
                'usable' => true,
            ],
            [
                'skin_id' => 115,
                'skin_model_name' => 'vla2',
                'name' => 'Varios Los Aztecas 2',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Varios Los Aztecas',
                'usable' => true,
            ],
            [
                'skin_id' => 116,
                'skin_model_name' => 'vla3',
                'name' => 'Varios Los Aztecas 3',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Varios Los Aztecas',
                'usable' => true,
            ],
            [
                'skin_id' => 117,
                'skin_model_name' => 'triada',
                'name' => 'Triad 1',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Triad',
                'usable' => true,
            ],
            [
                'skin_id' => 118,
                'skin_model_name' => 'triadb',
                'name' => 'Triad 2',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Triad',
                'usable' => true,
            ],
            [
                'skin_id' => 119,
                'skin_model_name' => 'sindaco',
                'name' => 'Johhny Sindacco',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Triad',
                'usable' => true,
            ],
            [
                'skin_id' => 120,
                'skin_model_name' => 'triboss',
                'name' => 'Triad Boss',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Triad',
                'usable' => true,
            ],
            [
                'skin_id' => 121,
                'skin_model_name' => 'dnb1',
                'name' => 'Da Nang Boy 1',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Da Nang Boys',
                'usable' => true,
            ],
            [
                'skin_id' => 122,
                'skin_model_name' => 'dnb2',
                'name' => 'Da Nang Boy 2',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Da Nang Boys',
                'usable' => true,
            ],
            [
                'skin_id' => 123,
                'skin_model_name' => 'dnb3',
                'name' => 'Da Nang Boy 3',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Da Nang Boys',
                'usable' => true,
            ],
            [
                'skin_id' => 124,
                'skin_model_name' => 'vmaff1',
                'name' => 'The Mafia 1',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'The Mafia',
                'usable' => true,
            ],
            [
                'skin_id' => 125,
                'skin_model_name' => 'vmaff2',
                'name' => 'The Mafia 2',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'The Mafia',
                'usable' => true,
            ],
            [
                'skin_id' => 126,
                'skin_model_name' => 'vmaff3',
                'name' => 'The Mafia 3',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'The Mafia',
                'usable' => true,
            ],
            [
                'skin_id' => 127,
                'skin_model_name' => 'vmaff4',
                'name' => 'The Mafia 4',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'The Mafia',
                'usable' => true,
            ],
            [
                'skin_id' => 128,
                'skin_model_name' => 'dnmylc',
                'name' => 'Farm Inhabitant',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 129,
                'skin_model_name' => 'dnfolc1',
                'name' => 'Farm Inhabitant',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 130,
                'skin_model_name' => 'dnfolc2',
                'name' => 'Farm Inhabitant',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 131,
                'skin_model_name' => 'dnfylc',
                'name' => 'Farm Inhabitant',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 132,
                'skin_model_name' => 'dnmolc1',
                'name' => 'Farm Inhabitant',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 133,
                'skin_model_name' => 'dnmolc2',
                'name' => 'Farm Inhabitant',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 134,
                'skin_model_name' => 'sbmotr2',
                'name' => 'Homeless',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 135,
                'skin_model_name' => 'swmotr2',
                'name' => 'Homeless',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 136,
                'skin_model_name' => 'sbmytr3',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 137,
                'skin_model_name' => 'swmotr3',
                'name' => 'Homeless',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 138,
                'skin_model_name' => 'wfybe',
                'name' => 'Beach Visitor',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 139,
                'skin_model_name' => 'bfybe',
                'name' => 'Beach Visitor',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 140,
                'skin_model_name' => 'hfybe',
                'name' => 'Beach Visitor',
                'gender' => 'female',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 141,
                'skin_model_name' => 'sofybu',
                'name' => 'Businesswoman',
                'gender' => 'female',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 142,
                'skin_model_name' => 'sbmyst',
                'name' => 'Taxi Driver',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 143,
                'skin_model_name' => 'sbmycr',
                'name' => 'Crack Maker',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 144,
                'skin_model_name' => 'bmycg',
                'name' => 'Crack Maker',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 145,
                'skin_model_name' => 'wfycrk',
                'name' => 'Crack Maker',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 146,
                'skin_model_name' => 'hmycm',
                'name' => 'Crack Maker',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 147,
                'skin_model_name' => 'wmybu',
                'name' => 'Businessman',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 148,
                'skin_model_name' => 'bfybu',
                'name' => 'Businesswoman',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 149,
                'skin_model_name' => 'smokev',
                'name' => 'Big Smoke Armored',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 150,
                'skin_model_name' => 'wfybu',
                'name' => 'Businesswoman',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 151,
                'skin_model_name' => 'dwfylc1',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 152,
                'skin_model_name' => 'wfypro',
                'name' => 'Prostitute',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 153,
                'skin_model_name' => 'wmyconb',
                'name' => 'Construction Worker',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 154,
                'skin_model_name' => 'wmybe',
                'name' => 'Beach Visitor',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 155,
                'skin_model_name' => 'wmypizz',
                'name' => 'Well Stacked Pizza Worker',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 156,
                'skin_model_name' => 'bmobar',
                'name' => 'Barber',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 157,
                'skin_model_name' => 'cwfyhb',
                'name' => 'Hillbilly',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 158,
                'skin_model_name' => 'cwmofr',
                'name' => 'Farmer',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 159,
                'skin_model_name' => 'cwmohb1',
                'name' => 'Hillbilly',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 160,
                'skin_model_name' => 'cwmohb2',
                'name' => 'Hillbilly',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 161,
                'skin_model_name' => 'cwmyfr',
                'name' => 'Farmer',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 162,
                'skin_model_name' => 'cwmyhb1',
                'name' => 'Hillbilly',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 163,
                'skin_model_name' => 'bmyboun',
                'name' => 'Black Bouncer',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 164,
                'skin_model_name' => 'wmyboun',
                'name' => 'White Bouncer',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 165,
                'skin_model_name' => 'wmomib',
                'name' => 'White MIB agent',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 166,
                'skin_model_name' => 'bmymib',
                'name' => 'Black MIB agent',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 167,
                'skin_model_name' => 'wmybell',
                'name' => 'Cluckin\' Bell Worker',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 168,
                'skin_model_name' => 'bmochil',
                'name' => 'Hotdog / Chilli Dog Vendor',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 169,
                'skin_model_name' => 'sofyri',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 170,
                'skin_model_name' => 'somyst',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 171,
                'skin_model_name' => 'vwmybjd',
                'name' => 'Blackjack Dealer',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 172,
                'skin_model_name' => 'vwfycrp',
                'name' => 'Casino croupier',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 173,
                'skin_model_name' => 'sfr1',
                'name' => 'San Fierro Rifa 1',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'San Fierro Rifa',
                'usable' => true,
            ],
            [
                'skin_id' => 174,
                'skin_model_name' => 'sfr2',
                'name' => 'San Fierro Rifa 2',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'San Fierro Rifa',
                'usable' => true,
            ],
            [
                'skin_id' => 175,
                'skin_model_name' => 'sfr3',
                'name' => 'San Fierro Rifa 3',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'San Fierro Rifa',
                'usable' => true,
            ],
            [
                'skin_id' => 176,
                'skin_model_name' => 'bmybar',
                'name' => 'Barber',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 177,
                'skin_model_name' => 'wmybar',
                'name' => 'Barber',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 178,
                'skin_model_name' => 'wfysex',
                'name' => 'Whore',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 179,
                'skin_model_name' => 'wmyammo',
                'name' => 'Ammunation Salesman',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 180,
                'skin_model_name' => 'bmytatt',
                'name' => 'Tattoo Artist',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 181,
                'skin_model_name' => 'vwmycr',
                'name' => 'Punk',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 182,
                'skin_model_name' => 'vbmocd',
                'name' => 'Cab Driver',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 183,
                'skin_model_name' => 'vbmycr',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 184,
                'skin_model_name' => 'vhmycr',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 185,
                'skin_model_name' => 'sbmyri',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 186,
                'skin_model_name' => 'somyri',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 187,
                'skin_model_name' => 'somybu',
                'name' => 'Businessman',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 188,
                'skin_model_name' => 'swmyst',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 189,
                'skin_model_name' => 'wmyva',
                'name' => 'Valet',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 190,
                'skin_model_name' => 'copgrl3',
                'name' => 'Barbara Schternvart',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 191,
                'skin_model_name' => 'gungrl3',
                'name' => 'Helena Wankstein',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 192,
                'skin_model_name' => 'mecgrl3',
                'name' => 'Michelle Cannes',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 193,
                'skin_model_name' => 'nurgrl3',
                'name' => 'Katie Zhan',
                'gender' => 'female',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 194,
                'skin_model_name' => 'crogrl3',
                'name' => 'Millie Perkins',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 195,
                'skin_model_name' => 'gangrl3',
                'name' => 'Denise Robinson',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 196,
                'skin_model_name' => 'cwfofr',
                'name' => 'Farm - Town inhabitant',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 197,
                'skin_model_name' => 'cwfohb',
                'name' => 'Hillbilly',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 198,
                'skin_model_name' => 'cwfyfr1',
                'name' => 'Farm - Town inhabitant',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 199,
                'skin_model_name' => 'cwfyfr2',
                'name' => 'Farm - Town inhabitant',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 200,
                'skin_model_name' => 'cwmyhb2',
                'name' => 'Hillbilly',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 201,
                'skin_model_name' => 'dwfylc2',
                'name' => 'Farmer',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 202,
                'skin_model_name' => 'dwmylc2',
                'name' => 'Farmer',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 203,
                'skin_model_name' => 'omykara',
                'name' => 'Karate Teacher',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 204,
                'skin_model_name' => 'wmykara',
                'name' => 'Karate Teacher',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 205,
                'skin_model_name' => 'wfyburg',
                'name' => 'Burger Shot Cashier',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 206,
                'skin_model_name' => 'vwmycd',
                'name' => 'Cab Driver',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 207,
                'skin_model_name' => 'vhfypro',
                'name' => 'Prostitute',
                'gender' => 'female',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 208,
                'skin_model_name' => 'suzie',
                'name' => 'Su Xi Mu(Suzie)',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 209,
                'skin_model_name' => 'omonood',
                'name' => 'Oriental Noodle stand vendor',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 210,
                'skin_model_name' => 'omoboat',
                'name' => 'Oriental Boating School Instructor',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 211,
                'skin_model_name' => 'wfyclot',
                'name' => 'Clothes shop staff',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 212,
                'skin_model_name' => 'vwmotr1',
                'name' => 'Homeless',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 213,
                'skin_model_name' => 'vwmotr2',
                'name' => 'Weird old man',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 214,
                'skin_model_name' => 'vwfywai',
                'name' => 'Waitress(Maria Latore)',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 215,
                'skin_model_name' => 'sbfori',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 216,
                'skin_model_name' => 'swfyri',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 217,
                'skin_model_name' => 'wmyclot',
                'name' => 'Clothes shop staff',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 218,
                'skin_model_name' => 'sbfost',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 219,
                'skin_model_name' => 'sbfyri',
                'name' => 'Rich Woman',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 220,
                'skin_model_name' => 'sbmocd',
                'name' => 'Cab Driver',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 221,
                'skin_model_name' => 'sbmori',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 222,
                'skin_model_name' => 'sbmost',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 223,
                'skin_model_name' => 'shmycr',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 224,
                'skin_model_name' => 'sofori',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 225,
                'skin_model_name' => 'sofost',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 226,
                'skin_model_name' => 'sofyst',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 227,
                'skin_model_name' => 'somobu',
                'name' => 'Oriental Businessman',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 228,
                'skin_model_name' => 'somori',
                'name' => 'Oriental Ped',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 229,
                'skin_model_name' => 'somost',
                'name' => 'Oriental Ped',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 230,
                'skin_model_name' => 'swmotr5',
                'name' => 'Homeless',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 231,
                'skin_model_name' => 'swfori',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 232,
                'skin_model_name' => 'swfost',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 233,
                'skin_model_name' => 'swfyst',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 234,
                'skin_model_name' => 'swmocd',
                'name' => 'Cab Driver',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 235,
                'skin_model_name' => 'swmori',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 236,
                'skin_model_name' => 'swmost',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 237,
                'skin_model_name' => 'shfypro',
                'name' => 'Prostitute',
                'gender' => 'female',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 238,
                'skin_model_name' => 'sbfypro',
                'name' => 'Prostitute',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 239,
                'skin_model_name' => 'swmotr4',
                'name' => 'Homeless',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 240,
                'skin_model_name' => 'swmyri',
                'name' => 'The D . A',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 241,
                'skin_model_name' => 'smyst',
                'name' => 'Afro - American',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 242,
                'skin_model_name' => 'smyst2',
                'name' => 'Mexican',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 243,
                'skin_model_name' => 'sfypro',
                'name' => 'Prostitute',
                'gender' => 'female',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 244,
                'skin_model_name' => 'vbfyst2',
                'name' => 'Stripper',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 245,
                'skin_model_name' => 'vbfypro',
                'name' => 'Prostitute',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 246,
                'skin_model_name' => 'vhfyst3',
                'name' => 'Stripper',
                'gender' => 'female',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 247,
                'skin_model_name' => 'bikera',
                'name' => 'Biker',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Biker',
                'usable' => true,
            ],
            [
                'skin_id' => 248,
                'skin_model_name' => 'bikerb',
                'name' => 'Biker',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Biker',
                'usable' => true,
            ],
            [
                'skin_id' => 249,
                'skin_model_name' => 'bmypimp',
                'name' => 'Pimp',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 250,
                'skin_model_name' => 'swmycr',
                'name' => 'Normal Ped',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 251,
                'skin_model_name' => 'wfylg',
                'name' => 'Lifeguard',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 252,
                'skin_model_name' => 'wmyva2',
                'name' => 'Naked Valet',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 253,
                'skin_model_name' => 'bmosec',
                'name' => 'Bus Driver',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 254,
                'skin_model_name' => 'bikdrug',
                'name' => 'Biker Drug Dealer',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Biker',
                'usable' => true,
            ],
            [
                'skin_id' => 255,
                'skin_model_name' => 'wmych',
                'name' => 'Chauffeur(Limo Driver)',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 256,
                'skin_model_name' => 'sbfystr',
                'name' => 'Stripper',
                'gender' => 'female',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 257,
                'skin_model_name' => 'swfystr',
                'name' => 'Stripper',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 258,
                'skin_model_name' => 'heck1',
                'name' => 'Heckler',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 259,
                'skin_model_name' => 'heck2',
                'name' => 'Heckler',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 260,
                'skin_model_name' => 'bmycon',
                'name' => 'Construction Worker',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 261,
                'skin_model_name' => 'wmycd1',
                'name' => 'Cab driver',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 262,
                'skin_model_name' => 'bmocd',
                'name' => 'Cab driver',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 263,
                'skin_model_name' => 'vwfywa2',
                'name' => 'Normal Ped',
                'gender' => 'female',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 264,
                'skin_model_name' => 'wmoice',
                'name' => 'Clown(Ice - cream Van Driver)',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 265,
                'skin_model_name' => 'tenpen',
                'name' => 'Officer Frank Tenpenny(Corrupt Cop)',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 266,
                'skin_model_name' => 'pulaski',
                'name' => 'Officer Eddie Pulaski(Corrupt Cop)',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 267,
                'skin_model_name' => 'hern',
                'name' => 'Officer Jimmy Hernandez',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 268,
                'skin_model_name' => 'dwayne',
                'name' => 'Dwaine / Dwayne',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 269,
                'skin_model_name' => 'smoke',
                'name' => 'Melvin "Big Smoke" Harris',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Grove Street Families',
                'usable' => false,
            ],
            [
                'skin_id' => 270,
                'skin_model_name' => 'sweet',
                'name' => 'Sean \'Sweet\' Johnson',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Grove Street Families',
                'usable' => false,
            ],
            [
                'skin_id' => 271,
                'skin_model_name' => 'ryder',
                'name' => 'Lance \'Ryder\' Wilson',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Grove Street Families',
                'usable' => true,
            ],
            [
                'skin_id' => 272,
                'skin_model_name' => 'forelli',
                'name' => 'Mafia Boss',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'The Mafia',
                'usable' => true,
            ],
            [
                'skin_id' => 273,
                'skin_model_name' => 'tbone',
                'name' => 'T - Bone Mendez',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 274,
                'skin_model_name' => 'laemt1',
                'name' => 'Paramedic(Emergency Medical Technician)',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 275,
                'skin_model_name' => 'lvemt1',
                'name' => 'Paramedic(Emergency Medical Technician)',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 276,
                'skin_model_name' => 'sfemt1',
                'name' => 'Paramedic(Emergency Medical Technician)',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 277,
                'skin_model_name' => 'lafd1',
                'name' => 'Firefighter',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 278,
                'skin_model_name' => 'lvfd1',
                'name' => 'Firefighter',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 279,
                'skin_model_name' => 'sffd1',
                'name' => 'Firefighter',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 280,
                'skin_model_name' => 'lapd1',
                'name' => 'Los Santos Police Officer',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 281,
                'skin_model_name' => 'sfpd1',
                'name' => 'San Fierro Police Officer',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 282,
                'skin_model_name' => 'lvpd1',
                'name' => 'Las Venturas Police Officer',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 283,
                'skin_model_name' => 'csher',
                'name' => 'County Sheriff',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 284,
                'skin_model_name' => 'lapdm1',
                'name' => 'LSPD Motorbike Cop',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 285,
                'skin_model_name' => 'swat',
                'name' => 'S.W.A.T Special Forces',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 286,
                'skin_model_name' => 'fbi',
                'name' => 'FBI Agent',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 287,
                'skin_model_name' => 'army',
                'name' => 'San Andreas Army Soldier',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 288,
                'skin_model_name' => 'dsher',
                'name' => 'Desert Sheriff',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 289,
                'skin_model_name' => 'zero',
                'name' => 'Zero',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 290,
                'skin_model_name' => 'rose',
                'name' => 'Ken Rosenberg',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 291,
                'skin_model_name' => 'paul',
                'name' => 'Kent Paul',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 292,
                'skin_model_name' => 'cesar',
                'name' => 'Cesar Vialpando',
                'gender' => 'male',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 293,
                'skin_model_name' => 'ogloc',
                'name' => 'Jeffery "OG Loc" Martin / Cross',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Grove Street Families',
                'usable' => false,
            ],
            [
                'skin_id' => 294,
                'skin_model_name' => 'wuzimu',
                'name' => 'Wu Zi Mu(Woozie)',
                'gender' => 'male',
                'race' => 'asian',
                'gang' => 'Civilian',
                'usable' => false,
            ],
            [
                'skin_id' => 295,
                'skin_model_name' => 'torino',
                'name' => 'Michael Toreno',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 296,
                'skin_model_name' => 'jizzy',
                'name' => 'Jizzy B . ',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 297,
                'skin_model_name' => 'maddogg',
                'name' => 'Madd Dogg',
                'gender' => 'male',
                'race' => 'black',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 298,
                'skin_model_name' => 'cat',
                'name' => 'Catalina',
                'gender' => 'female',
                'race' => 'hispanic',
                'gang' => 'Civilian',
                'usable' => true,
            ],
            [
                'skin_id' => 299,
                'skin_model_name' => 'claude',
                'name' => 'Claude Speed',
                'gender' => 'male',
                'race' => 'white',
                'gang' => 'Civilian',
                'usable' => true,
            ],

        ];

        DB::table('skin_data')->upsert(
            $skins,
            ['skin_id'],
            ['skin_model_name', 'name', 'gender', 'race', 'gang', 'usable']
        );

    }
}

/*
 *     [
            'skin_id' => ,
            'skin_model_name' => '',
            'name' => '',
            'gender' => '',
            'race' => '',
            'gang' => '',
            'usable' => ,
        ],
 */
